Table event {
  id integer [primary key]
  name varchar
  start_time datetime
  end_time datetime
  location varchar
}

Table profile {
  id integer [primary key]
  name varchar
}

Table eventxprofile {
  id integer [primary key]
  eventid integer [ref: > event.id]
  profileid integer [ref: > profile.id]
}
